// Codex pages: Kits, Crates and Chat Tags. Data comes from /static/codex.json,
// generated by scripts/codex/build_codex.py from the wiki and in-game captures.
// Wrapped in an IIFE so its names can't collide with app.js; app.js calls
// window.codexShow(page) from navigate().
(() => {
  const CODEX_DATA_VERSION = 1;  // bump with every regenerated codex.json
  const $ = (s, r = document) => r.querySelector(s);
  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const iconUrl = (stem) => `/static/icons/${stem}.png`;

  let data = null;
  let loading = null;

  const RARITY = {  // the colours the crates use in-game (from the captures), same as the tag crate keys
    'Exceedingly Rare': '#ffaa00', 'Super Rare': '#ffff55', 'Very Rare': '#ff5555',
    'Rare': '#ff55ff', 'Uncommon': '#aa00aa', 'Common': '#55ffff',
  };

  // Minecraft text in the pack font: every glyph casts a shadow of its own colour at 1/4
  // brightness, one font pixel (2px) down-right; bold redraws the glyph one pixel over.
  function mcShadow(hex) {
    const n = parseInt(hex.slice(1), 16);
    const q = (v) => ((v >> 2) & 0x3f).toString(16).padStart(2, '0');
    return '#' + q(n >> 16 & 255) + q(n >> 8 & 255) + q(n & 255);
  }
  function mcStyle(color, bold) {
    const sh = mcShadow(color);
    return bold
      ? `color:${color};letter-spacing:2px;text-shadow:2px 0 0 ${color},2px 2px 0 ${sh},4px 2px 0 ${sh}`
      : `color:${color};text-shadow:2px 2px 0 ${sh}`;
  }
  const mcSpan = (text, color = '#ffffff', bold = false) => `<span style="${mcStyle(color, bold)}">${esc(text)}</span>`;
  const RARITY_ORDER = Object.keys(RARITY);

  // ── Enchant lookup: "Soulbound III" -> the wiki's description ──
  const baseName = (e) => e.replace(/\s+([IVX]+|\d+)$/, '').replace(/\s*\(.*\)$/, '');
  function enchDesc(e) {
    const clean = e.replace(/\s*\(.*\)$/, '').trim();
    const E = data.enchants;
    return E[clean] || E[baseName(clean)] || E[baseName(clean) + ' I'] || '';
  }

  // ── Inventory slots and the Minecraft-style tooltip ──
  const tipItems = [];
  function slot(item, extraClass = '') {
    const id = tipItems.push(item) - 1;
    const enchanted = item.e && item.e.length && item.icon;
    const mask = enchanted ? ` style="--m:url(${iconUrl(item.icon)})"` : '';
    const block = item.icon && item.icon.startsWith('block/') ? ' class="is-block"' : '';  // 3D render, scale smoothly
    const inner = item.icon
      ? `<img src="${iconUrl(item.icon)}"${block} alt="" loading="lazy" width="32" height="32">`
      : '<span class="codex-swatch"></span>';
    const count = item.c > 1 ? `<span class="codex-count">${item.c}</span>` : '';
    const label = (item.c > 1 ? item.c + ' ' : '') + item.n;
    return `<button type="button" class="codex-slot${enchanted ? ' is-ench' : ''} ${extraClass}" data-tip="${id}" aria-label="${esc(label)}"${mask}>${inner}${count}</button>`;
  }
  function tipHTML(t) {
    const color = t.rarity ? RARITY[t.rarity] : (t.e && t.e.length ? '#55ffff' : '#ffffff');
    let h = `<div class="codex-tip-name">${mcSpan(t.n, color)}</div>`;
    (t.e || []).forEach((e) => {
      h += `<div class="codex-tip-line">${esc(e)}</div>`;
      const d = enchDesc(e);
      if (d) h += `<div class="codex-tip-desc">${esc(d)}</div>`;
    });
    if (t.note) h += `<div class="codex-tip-line">${esc(t.note)}</div>`;
    if (t.d) h += `<div class="codex-tip-line">${esc(t.d)}</div>`;
    if (t.usage) h += `<div class="codex-tip-line">Use: ${esc(t.usage)}</div>`;
    if (t.charges) h += `<div class="codex-tip-meta">${t.charges} charges</div>`;
    if (t.c > 64) h += `<div class="codex-tip-meta">${t.c} items · ${+(t.c / 64).toFixed(1)} stacks</div>`;
    if (t.rarity) h += `<div class="codex-tip-meta">${esc(t.rarity)}</div>`;
    if (t.odds != null) h += `<div class="codex-tip-meta">${t.odds}% per key</div>`;
    return h;
  }

  let tip = null;
  let tipFor = null;
  const finePointer = matchMedia('(hover: hover) and (pointer: fine)').matches;
  function showTip(el, html) {
    tip.dataset.instant = tip.dataset.open === 'true' ? 'true' : 'false';  // no fade when moving slot to slot
    tip.innerHTML = html;
    const r = el.getBoundingClientRect();
    const tw = tip.offsetWidth;
    const th = tip.offsetHeight;
    let x = r.right + 8;
    let y = r.top - 4;
    let origin = 'top left';
    if (x + tw > innerWidth - 8) { x = Math.max(8, r.left - tw - 8); origin = 'top right'; }
    if (innerWidth < 560 || x < 8) { x = Math.min(Math.max(8, r.left), innerWidth - tw - 8); y = r.bottom + 8; origin = 'top left'; }
    if (y + th > innerHeight - 8) y = Math.max(8, r.top - th - 8);
    tip.style.left = x + 'px';
    tip.style.top = y + 'px';
    tip.style.setProperty('--origin', origin);
    tip.dataset.open = 'true';
    tipFor = el;
  }
  function hideTip() { if (tip) tip.dataset.open = 'false'; tipFor = null; }
  function openTipFor(el) {
    if (el.dataset.tip) return showTip(el, tipHTML(tipItems[el.dataset.tip]));
    showTip(el, `<div class="codex-tip-name">${mcSpan(el.dataset.ench, '#ff55ff')}</div>
      <div class="codex-tip-desc codex-tip-desc--flush">${esc(enchDesc(el.dataset.ench))}</div>`);
  }
  function wireTooltip() {
    tip = document.createElement('div');
    tip.className = 'codex-tip';
    tip.setAttribute('role', 'tooltip');
    tip.dataset.open = 'false';
    document.body.appendChild(tip);
    const target = (e) => e.target.closest?.('.codex-page [data-tip], .codex-page [data-ench]');
    if (finePointer) {
      document.addEventListener('mouseover', (e) => { const el = target(e); if (el) openTipFor(el); });
      document.addEventListener('mouseout', (e) => { const el = target(e); if (el && !el.contains(e.relatedTarget)) hideTip(); });
    }
    document.addEventListener('click', (e) => {
      const el = target(e);
      if (!el) return hideTip();
      if (tipFor === el && !finePointer) hideTip(); else openTipFor(el);
    });
    document.addEventListener('focusin', (e) => { const el = target(e); if (el) openTipFor(el); });
    document.addEventListener('focusout', hideTip);
    document.addEventListener('keydown', (e) => { if (e.key === 'Escape') hideTip(); });
    addEventListener('scroll', hideTip, { passive: true });
  }

  function segment(sel, onChange) {
    $(sel).addEventListener('click', (e) => {
      const b = e.target.closest('button');
      if (!b) return;
      $(sel).querySelectorAll('button').forEach((x) => x.setAttribute('aria-pressed', String(x === b)));
      onChange(b.dataset.v);
    });
  }

  // ── Kits ──
  const KIT_SECTIONS = [
    ['Everyone', 'Available from day one'],
    ['Ranks', 'Unlock by ranking up, before any prestige'],
    ['Prestige', 'Unlock by reaching a rank inside a prestige'],
    ['Master Prestige', 'The last tier'],
    ['Cop brewing', 'Ingredients for the cop drinks'],
    ['Store ranks', 'Bought on the store'],
  ];
  function kitSection(k) {
    if (k.group === 'store') return 'Store ranks';
    if (k.group === 'brewing') return 'Cop brewing';
    if (k.unlocks.some((u) => u.label === 'Everyone')) return 'Everyone';
    if (k.unlocks.some((u) => u.tier === 99)) return 'Master Prestige';
    if (k.unlocks.some((u) => u.tier > 0)) return 'Prestige';
    return 'Ranks';
  }
  const kitSort = (k) => Math.min(...k.unlocks.map((u) => u.tier * 100 + u.rank));
  function unlockChip(u) {
    if (u.track === 'store') return `<span class="codex-chip codex-chip--store">${esc(u.label)}</span>`;
    if (u.label === 'Everyone') return '<span class="codex-chip">Everyone</span>';
    const label = u.label.replace(/^Prestige (\d+) /, 'P$1 ').replace(/^Master Prestige /, 'Master ').replace('DeputyChief', 'Deputy Chief');
    return `<span class="codex-chip codex-chip--${u.track}">${u.track === 'cop' ? 'Cop' : 'Chem'} · ${esc(label)}</span>`;
  }
  function cooldown(cd) {
    const txt = cd === '1 Day' ? 'daily' : 'every ' + cd.replace(' Hours', 'h');
    return `<span class="codex-cooldown"><svg viewBox="0 0 12 12" fill="none" aria-hidden="true"><circle cx="6" cy="6" r="4.8" stroke="currentColor" stroke-width="1.3"/><path d="M6 3.5V6l1.6 1.2" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/></svg>${txt}</span>`;
  }
  let kitTrack = 'all';
  function kitMatchesTrack(k) {
    if (kitTrack === 'all') return true;
    if (kitTrack === 'store') return k.group === 'store';
    if (k.group === 'store') return false;
    return k.unlocks.some((u) => u.track === kitTrack || u.label === 'Everyone');
  }
  function renderKits() {
    const q = $('#codex-kit-q').value.trim().toLowerCase();
    const hit = (it) => q && it.n.toLowerCase().includes(q);
    const kits = data.kits.filter(kitMatchesTrack).filter((k) => !q || k.name.toLowerCase().includes(q) || k.items.some(hit));
    const out = $('#codex-kit-out');
    out.classList.toggle('is-searching', !!q);
    $('#codex-kit-result').innerHTML = q
      ? (kits.length ? `<b>${kits.length}</b> ${kits.length === 1 ? 'kit has' : 'kits have'} “${esc(q)}”` : '')
      : `${kits.length} kits`;
    if (!kits.length) {
      out.innerHTML = `<div class="card codex-empty">No kit gives “${esc(q)}”. <button type="button" data-search-crates="${esc(q)}">Search the crates instead</button></div>`;
      return;
    }
    // One card per section, one row per kit: command and cooldown, who unlocks it, what's inside.
    out.innerHTML = KIT_SECTIONS.map(([sec, note]) => {
      const list = kits.filter((k) => kitSection(k) === sec).sort((a, b) => kitSort(a) - kitSort(b));
      if (!list.length) return '';
      return `<section class="card codex-group">
        <header class="codex-group-head"><h3>${sec}</h3><span class="codex-group-note">${note}</span></header>
        ${list.map((k) => `
        <div class="codex-kit-row">
          <div class="codex-kit-cmd"><div><span>/kit </span>${esc(k.name.toLowerCase())}</div>${cooldown(k.cooldown)}</div>
          <div class="codex-chips">${k.unlocks.filter((u) => u.label !== 'Everyone').map(unlockChip).join('')}</div>
          <div class="codex-slots">${k.items.map((it) => slot(it, hit(it) ? 'is-hit' : '')).join('')}</div>
        </div>`).join('')}
      </section>`;
    }).join('');
  }

  // ── Crates ──
  const CRATE_GROUPS = ['Vote', 'Prestige', 'Supply', 'Store', 'Seasonal', 'Tags'];
  let crateSel = 'Voter Crate';
  const crateSize = (c) => (c.tagCrate ? c.tags.length : c.items.length);
  function renderCrateNav() {
    const q = $('#codex-crate-q').value.trim();
    $('#codex-crate-nav').innerHTML = CRATE_GROUPS.map((g) => `<div class="codex-crate-grp"><div class="codex-grp-label">${g}</div>${
      data.crates.filter((c) => c.group === g).map((c) => `
        <button type="button" class="codex-crate-pick" aria-pressed="${!q && c.name === crateSel}" data-crate="${esc(c.name)}">${esc(c.name.replace(' Crate', ''))}<small>${crateSize(c)}</small></button>`).join('')
    }</div>`).join('');
  }
  function pickCrate(name) { crateSel = name; $('#codex-crate-q').value = ''; renderCrates(true); }
  function enchChips(list) {
    if (!list.length) return '';
    return `<div class="codex-chips">${list.map((e) => (enchDesc(e)
      ? `<button type="button" class="codex-ench is-custom" data-ench="${esc(e)}">${esc(e)}</button>`
      : `<span class="codex-ench">${esc(e)}</span>`)).join('')}</div>`;
  }
  function itemMeta(it) {
    const bits = [];
    if (it.usage) bits.push(`<code class="codex-cmd">${esc(it.usage)}</code>`);
    if (it.charges) bits.push(`<span class="codex-meta">${it.charges} charges</span>`);
    if (it.unboxed) bits.push(`<span class="codex-meta">${it.unboxed} unboxed so far</span>`);
    return bits.length ? `<div class="codex-row-meta">${bits.join('')}</div>` : '';
  }
  function itemRow(it, maxOdds) {
    const color = it.color || (it.rarity ? RARITY[it.rarity] : '#fff');
    const odds = it.odds != null
      ? `<div class="codex-row-odds"><b>${it.odds}%</b><span>1 in ${Math.round(100 / it.odds)} keys</span><div class="codex-bar"><i style="width:${(it.odds / maxOdds) * 100}%"></i></div></div>`
      : '<div></div>';
    return `<div class="codex-row">${slot(it)}<div><div class="codex-row-name" style="color:${color}">${esc(it.n)}</div>${
      it.d ? `<div class="codex-row-desc">${esc(it.d)}</div>` : ''}${enchChips(it.e)}${itemMeta(it)}</div>${odds}</div>`;
  }
  function crateItemsHTML(c) {
    if (c.items[0].odds != null) {
      const items = [...c.items].sort((a, b) => a.odds - b.odds);
      const max = Math.max(...items.map((i) => i.odds));
      return items.map((i) => itemRow(i, max)).join('');
    }
    return RARITY_ORDER.map((r) => {
      const items = c.items.filter((i) => i.rarity === r);
      return items.length ? `<div class="codex-rarity" style="--rule:${RARITY[r]}">${mcSpan(r, RARITY[r])}</div>${items.map((i) => itemRow(i)).join('')}` : '';
    }).join('');
  }
  const tagChip = (t) => `<button type="button" class="codex-tag-chip" data-tag="${t.id}" aria-pressed="${t.id === tagSel}" title="Try it in chat">${renderTag(t)}</button>`;
  function crateHead(c, right) {
    const keys = esc(c.keys).replace(/(^|\s)(\/\w+)/g, '$1<code>$2</code>');
    const src = c.source === 'wiki' ? ' <span class="codex-src" title="Not captured in-game yet">wiki data</span>' : '';
    return `<div class="card codex-crate-head"><div><h3>${esc(c.name)}${src}</h3>
      <div class="codex-keyline"><img src="${iconUrl('tripwire_hook')}" alt="" width="20" height="20"><span>${keys}</span></div></div>${right || ''}</div>`;
  }
  function renderCrates(swap) {
    renderCrateNav();
    const q = $('#codex-crate-q').value.trim().toLowerCase();
    const main = $('#codex-crate-main');
    if (q) {
      const hits = data.crates.map((c) => ({
        c,
        items: c.tagCrate ? [] : c.items.filter((i) => `${i.n} ${i.d} ${i.e.join(' ')}`.toLowerCase().includes(q)),
        tags: c.tagCrate ? c.tags.map((id) => data.tags[id]).filter((t) => t.text.toLowerCase().includes(q)) : [],
      })).filter((h) => h.items.length || h.tags.length);
      const n = hits.reduce((s, h) => s + h.items.length + h.tags.length, 0);
      main.innerHTML = `<div class="card codex-crate-head"><div><h3>“${esc(q)}”</h3><div class="codex-keyline">${
        n ? `${n} match${n > 1 ? 'es' : ''} in ${hits.length} crate${hits.length > 1 ? 's' : ''}` : 'Nothing matches. Try an enchant like Soulbound, or a tag name.'}</div></div></div>
        ${hits.length ? `<div class="card codex-crate-body">${hits.map((h) => `<div class="codex-hit-crate"><button type="button" data-crate="${esc(h.c.name)}">${esc(h.c.name)} →</button></div>${
          h.tags.length ? `<div class="codex-tag-grid">${h.tags.map(tagChip).join('')}</div>`
            : h.items.map((i) => itemRow(i, Math.max(...h.c.items.map((x) => x.odds || 0)))).join('')}`).join('')}</div>` : ''}`;
      return;
    }
    const c = data.crates.find((x) => x.name === crateSel);
    if (c.tagCrate) {
      main.innerHTML = crateHead(c, `<div class="codex-crate-top"><b style="color:${c.color}">${c.chance}% each</b><span>${c.tags.length} tags, equal odds</span></div>`)
        + `<div class="card codex-crate-body" data-swap="${!!swap}"><div class="codex-tag-grid">${c.tags.map((id) => tagChip(data.tags[id])).join('')}</div>
           <div class="codex-note">A Tag Key Crate Key rolls this crate ${c.keyChance}% of the time. Tap a tag to try it in chat.</div></div>`;
      return;
    }
    const top = c.items[0].odds != null ? [...c.items].sort((a, b) => a.odds - b.odds)[0] : c.items.find((i) => i.rarity === 'Exceedingly Rare');
    const topSub = top && (top.odds != null ? `rarest · 1 in ${Math.round(100 / top.odds)} keys`
      : top.unboxed ? `the chase item · ${top.unboxed} unboxed so far` : 'the chase item');
    main.innerHTML = crateHead(c, top ? `<div class="codex-crate-top"><b style="color:${top.rarity ? RARITY[top.rarity] : 'var(--mc-gold)'}">${esc(top.n)}</b><span>${topSub}</span></div>` : '')
      + `<div class="card codex-crate-body" data-swap="${!!swap}">${crateItemsHTML(c)}${c.items[0].odds == null
        ? '<div class="codex-note">You get the highest rarity rolled, and every key you open raises your odds of a Rare or better. Left-click the crate in-game to see your current roll. Scrap unwanted items for new keys with <code>/scrap</code>.</div>' : ''}</div>`;
  }

  // ── Chat tags ──
  function renderTag(t) {
    if (t.img) return `<img class="codex-tag-img" src="/static/icons/tags/${t.img}.png" alt="${esc(t.text)}">`;
    if (!t.segs) return `<span class="codex-mc">${mcSpan(t.text)}</span>`;
    return `<span class="codex-mc">${t.segs.map((p) => mcSpan(p.t, p.c, p.b)).join('')}</span>`;
  }
  const FILTERS = { event: ['event'], pit: ['pit'], crate: ['crate'], shop: ['shop'], earned: ['achievement', 'vote', 'earned'], other: ['other'] };
  const HOLDERS_SHOWN = 4;
  const expanded = new Set();
  let tagFilter = 'all';
  let tagSel = 0;
  let scrollToTag = false;  // set when a crate sends you here with a tag picked
  const shortDate = (iso) => new Date(iso + 'T12:00:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
  function holdersHTML(t) {
    if (!t.holders || !t.holders.length) return '';  // null: still running, the header says so
    const open = expanded.has(t.id) || t.holders.length <= HOLDERS_SHOWN + 1;
    const names = (open ? t.holders : t.holders.slice(0, HOLDERS_SHOWN)).map((h) => `<b>${esc(h)}</b>`).join(', ');
    const more = open ? '' : ` <button type="button" data-more="${t.id}">+${t.holders.length - HOLDERS_SHOWN} more</button>`;
    return `<span class="codex-holders">Held by ${names}${more}</span>`;
  }
  // Each category is one card: a heading line, then rows (tags you earn by placing or doing
  // something, with holders) or a chip grid (tags that share one way of getting them).
  const ROW_GROUPS = new Set(['event', 'pit', 'achievement', 'vote']);
  const tagRow = (t) => `
    <div class="codex-tag-row" role="button" tabindex="0" aria-pressed="${t.id === tagSel}" data-tag="${t.id}">
      <div class="codex-tag-cell">${renderTag(t)}</div>
      <div class="codex-tag-how">${esc(t.how)}</div>
      <div class="codex-tag-who">${holdersHTML(t)}</div>
    </div>`;
  function renderChat() {
    const name = $('#codex-chat-name').value.trim() || 'Steve';
    $('#codex-chat-line').innerHTML = `${mcSpan('[Director]', '#aaaaaa')} ${renderTag(data.tags[tagSel])} ${mcSpan(name + ': gg')}`;
  }
  function groupHead(s) {
    const note = s.live
      ? `<span class="codex-status codex-status--live">Live${s.ends ? ' · ends ' + shortDate(s.ends) : ''}</span>`
      : `<span class="codex-group-note">${esc(s.note || '')}</span>`;
    const color = s.color ? ` style="color:${s.color}"` : '';  // tag crates wear their key's colour
    return `<header class="codex-group-head"><h3${color}>${esc(s.name)}</h3>${note}</header>`;
  }
  function renderTags() {
    const q = $('#codex-tag-q').value.trim().toLowerCase();
    const groups = FILTERS[tagFilter];
    let html = '';
    data.tagSections.forEach((s) => {
      if (groups && !groups.includes(s.group)) return;
      const inSection = s.name.toLowerCase().includes(q);  // "pit" finds every Pit Weekend tag
      const list = data.tags.filter((t) => t.section === s.id
        && (!q || inSection || t.text.toLowerCase().includes(q) || (t.how || '').toLowerCase().includes(q)));
      if (!list.length) return;
      const body = ROW_GROUPS.has(s.group) || s.layout === 'rows'
        ? `<div class="codex-tag-rows">${list.map(tagRow).join('')}</div>`
        : `<div class="codex-tag-grid">${list.map((t) => tagChip(t).replace('title="Try it in chat"', `title="${esc(t.how)}"`)).join('')}</div>`;
      html += `<section class="card codex-group${s.id === 'unsorted' ? ' is-unknown' : ''}">${groupHead(s)}${body}</section>`;
    });
    $('#codex-tag-out').innerHTML = html || `<div class="card codex-empty">No tag matches “${esc(q)}”.</div>`;
    renderChat();
  }
  function selectTag(id) {
    tagSel = id;
    document.querySelectorAll('#codex-tag-out [aria-pressed="true"]').forEach((el) => el.setAttribute('aria-pressed', 'false'));
    document.querySelectorAll(`#codex-tag-out [data-tag="${id}"]`).forEach((el) => el.setAttribute('aria-pressed', 'true'));
    renderChat();
  }

  // ── Wiring ──
  let wired = false;
  function wire() {
    wired = true;
    wireTooltip();
    $('#codex-kit-q').addEventListener('input', renderKits);
    segment('#codex-kit-track', (v) => { kitTrack = v; renderKits(); });
    $('#codex-kit-out').addEventListener('click', (e) => {
      const b = e.target.closest('[data-search-crates]');
      if (b) { $('#codex-crate-q').value = b.dataset.searchCrates; location.hash = '#crates'; }
    });
    $('#codex-crate-q').addEventListener('input', () => renderCrates(false));
    $('#codex-crate-nav').addEventListener('click', (e) => { const b = e.target.closest('[data-crate]'); if (b) pickCrate(b.dataset.crate); });
    $('#codex-crate-main').addEventListener('click', (e) => {
      const c = e.target.closest('[data-crate]');
      if (c) return pickCrate(c.dataset.crate);
      const t = e.target.closest('[data-tag]');
      if (!t) return;
      tagSel = +t.dataset.tag;
      scrollToTag = true;
      location.hash = '#tags';
    });
    $('#codex-tag-q').addEventListener('input', renderTags);
    $('#codex-chat-name').addEventListener('input', renderChat);
    segment('#codex-tag-filter', (v) => { tagFilter = v; renderTags(); });
    // hide filters with nothing under them (e.g. "Other" once every tag has a source)
    document.querySelectorAll('#codex-tag-filter [data-v]').forEach((b) => {
      const groups = FILTERS[b.dataset.v];
      b.hidden = !!groups && !data.tagSections.some((sec) => groups.includes(sec.group));
    });
    $('#codex-tag-out').addEventListener('click', (e) => {
      const more = e.target.closest('[data-more]');
      if (more) { expanded.add(+more.dataset.more); renderTags(); return; }
      const el = e.target.closest('[data-tag]');
      if (el) selectTag(+el.dataset.tag);
    });
    $('#codex-tag-out').addEventListener('keydown', (e) => {
      const el = e.target.closest('div[data-tag]');
      if (el && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); selectTag(+el.dataset.tag); }
    });
  }

  const RENDER = { kits: renderKits, crates: () => renderCrates(false), tags: renderTags };

  function load() {
    loading = loading || fetch(`/static/codex.json?v=${CODEX_DATA_VERSION}`)
      .then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then((json) => { data = json; });
    return loading;
  }

  window.codexShow = async (page) => {
    const out = $(`#page-${page} .codex-body`);
    if (!data) {
      try {
        await load();
      } catch (err) {
        loading = null;
        console.error('codex: could not load data', err);
        out.insertAdjacentHTML('afterbegin', '<div class="card codex-empty codex-load-error">Couldn\'t load the Codex. Check your connection and reload the page.</div>');
        return;
      }
    }
    out.querySelector('.codex-load-error')?.remove();
    if (!wired) wire();
    document.documentElement.style.setProperty('--codex-hdr', document.querySelector('header').offsetHeight + 'px');
    if (page === 'tags' && tagSel >= data.tags.length) tagSel = 0;
    RENDER[page]();
    if (page === 'tags' && scrollToTag) {
      scrollToTag = false;
      requestAnimationFrame(() => $(`#codex-tag-out [data-tag="${tagSel}"]`)?.scrollIntoView({ block: 'center' }));
    }
  };
})();
